/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.gui;
import java.awt.image.ImageFilter;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import ufps.util.ExceptionUFPS;


/**
 *
 * @author Leonar
 */
public class FormPrinciapal extends javax.swing.JFrame {

    public FormPrinciapal() {
        initComponents();
        this.iniciar();
    }

    /**
     * Metodo que inicia el Form de manera que no se pueda 
     * modificar su tamaño
     */
    private void iniciar() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelAlto = new javax.swing.JTextField();
        btnEnviarTamano = new javax.swing.JButton();
        labelAncho = new javax.swing.JTextField();
        btnImagenUpload = new javax.swing.JButton();
        labelImagenUpload = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(667, 700));
        setMinimumSize(new java.awt.Dimension(667, 700));
        setPreferredSize(new java.awt.Dimension(667, 700));

        panelInicial.setMaximumSize(new java.awt.Dimension(657, 660));
        panelInicial.setMinimumSize(new java.awt.Dimension(657, 660));
        panelInicial.setPreferredSize(new java.awt.Dimension(657, 660));

        jLabel1.setText("Por favor ingrese el tamaño  de la imagen");

        jLabel2.setText("Ancho: ");

        jLabel3.setText("Alto: ");

        btnEnviarTamano.setText("Enviar");
        btnEnviarTamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTamanoActionPerformed(evt);
            }
        });

        btnImagenUpload.setText("Seleccione la Imagen");
        btnImagenUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenUploadActionPerformed(evt);
            }
        });

        labelImagenUpload.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setText("Mapa de Bits");

        jLabel5.setText("Imagen: ");

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEnviarTamano)
                .addGap(57, 57, 57))
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInicialLayout.createSequentialGroup()
                                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelInicialLayout.createSequentialGroup()
                                        .addComponent(labelImagenUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnImagenUpload))))
                            .addGroup(panelInicialLayout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel4)))
                        .addGap(82, 82, 82))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImagenUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagenUpload)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarTamano)
                .addGap(46, 46, 46))
        );

        labelBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/imagen/banner.png"))); // NOI18N
        labelBanner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        labelBanner.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                labelBannerComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void labelBannerComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_labelBannerComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBannerComponentAdded

    /**
     * 
     * @param an
     * @param al
     * @return true si las variables ancho o alto son diferentes de "", y el ancho y alto
     * numerico sea mayor a cero "0" en caso contrario false.
     */
    
    
    
    private boolean validoRangos(String an ,String al) throws Exception
    {
        if((Integer.parseInt(an)>0 && Integer.parseInt(an)<=50) && (Integer.parseInt(al)>0 && Integer.parseInt(al)<=50))
            return true;
        
        return false;
    }
    
    private void validaciones(String ancho,String alto) throws Exception
    {
        if(!this.validoRangos(alto,ancho) || (ancho.equals("") || alto.equals("") && !this.labelImagenUpload.getText().equals("")))
            throw new Exception();
    }
    
    
    /**
     * Boton que permite crear una imagen de pixeles, dados un ancho y un alto.
     * Si en caso de seleccionar una imagen del equipo y el ancho y alto se encuentre vacios
     * Si en caso de seleccionar una imagen del equipo y el ancho y alto se encuentre vacios
     * generara la imagen del ancho maximo y asi el alto.
     * @param evt 
     */
    private void btnEnviarTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTamanoActionPerformed
        // TODO add your handling code here:
        try {
            String ancho = this.labelAncho.getText();
            String alto = this.labelAlto.getText();
            String img = this.labelImagenUpload.getText();
            panelInicial.setVisible(false);
            
            JPanel panelImg;
            
                this.validaciones(ancho,alto);      
               
            panelImg = new PanelImagen(Integer.parseInt(alto),Integer.parseInt(ancho), img);
            panelImg.setBounds(0, 105, 667, 670);
            this.getContentPane().add(panelImg);
               
        } 
        catch(Exception x) 
        {
           JOptionPane.showMessageDialog(rootPane,"Los datos ingresados no son validos","",0);
            panelInicial.setVisible(true);
        }
        
    }//GEN-LAST:event_btnEnviarTamanoActionPerformed

    /**
     * 
     * @param ancho
     * @param alto
     * @return true si las variable ancho o alto son diferentes de "", 
     * en caso contratio false
     */
    private boolean validos(String ancho , String alto)
    {
        if(!ancho.equals("") && !alto.equals(""))
            return true;
        
        return false;
    }
    
    
    /**
     * Boton que permite cargar una imagen formato : jpg, png, mbp, gif.
     * Desde el equipo para poder proyectarlo como una imagen pixelada.
     * @param evt 
     */
    private void btnImagenUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenUploadActionPerformed
        // TODO add your handling code here:
        
        try
        {
          
            

            
            
        JFileChooser input = new JFileChooser();
        input.setMultiSelectionEnabled(false);
        input.setAcceptAllFileFilterUsed(false);        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        input.setFileFilter(filter);
        
        input.setAcceptAllFileFilterUsed(false);

        int result = input.showSaveDialog(this);
        
        
        if (result == JFileChooser.APPROVE_OPTION) 
        {
        File f = input.getSelectedFile();
        this.labelImagenUpload.setText(f.getAbsolutePath());
        } 
        else if (result == JFileChooser.CANCEL_OPTION) {
        }
          
        }catch(Exception ufps)
        {
            System.out.println(ufps.getMessage());
        }
    }//GEN-LAST:event_btnImagenUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrinciapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrinciapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrinciapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrinciapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrinciapal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarTamano;
    private javax.swing.JButton btnImagenUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField labelAlto;
    private javax.swing.JTextField labelAncho;
    private javax.swing.JLabel labelBanner;
    private javax.swing.JTextField labelImagenUpload;
    private javax.swing.JPanel panelInicial;
    // End of variables declaration//GEN-END:variables
}
