/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.Random;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.border.Border;
import ufps.negocio.HSLColor;
import ufps.negocio.Imagen;

 
        // creates radio button and set corresponding action
        // commands
/**
 *
 * @author Leonar 
 */
public class PanelImagen extends javax.swing.JPanel {

    /**
     * Creates new form PanelImagen
     */
    private Imagen p;
    private JTextField matrizBotones[][];
    //private Component frame;
    
    public PanelImagen(int alto, int ancho, String img) throws IOException 
    {
        initComponents();
        this.p = new Imagen(alto, ancho, img);
        beepForAnHour();
        this.bntFlipHorizontal.putClientProperty("JButton.buttonType", "bevel");
    }

    private static final ScheduledExecutorService worker= Executors.newSingleThreadScheduledExecutor();

    void beepForAnHour() {
        Runnable task = new Runnable() {
            public void run() {
                crear();
            }
        };
        worker.schedule(task, 1, TimeUnit.SECONDS);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPatronGama = new javax.swing.JDialog();
        checkRedPatron = new javax.swing.JCheckBox();
        checkGreenPatron = new javax.swing.JCheckBox();
        checkBluePatron = new javax.swing.JCheckBox();
        btnEnviarPatron = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelColor2Patron = new javax.swing.JLabel();
        labelColor1Patron = new javax.swing.JLabel();
        labelColor3Patron = new javax.swing.JLabel();
        labelColor4Patron = new javax.swing.JLabel();
        labelColor5Patron = new javax.swing.JLabel();
        labelColor6Patron = new javax.swing.JLabel();
        labelColor7Patron = new javax.swing.JLabel();
        labelColor8Patron = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGroup = new javax.swing.ButtonGroup();
        dialogInvertirGama = new javax.swing.JDialog();
        checkRedGama = new javax.swing.JCheckBox();
        checkGreenGama = new javax.swing.JCheckBox();
        checkBlueGama = new javax.swing.JCheckBox();
        btnEnviarGama = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelColor2Gama = new javax.swing.JLabel();
        labelColor1Gama = new javax.swing.JLabel();
        labelColor3Gama = new javax.swing.JLabel();
        labelColor4Gama = new javax.swing.JLabel();
        labelColor5Gama = new javax.swing.JLabel();
        labelColor6Gama = new javax.swing.JLabel();
        labelColor7Gama = new javax.swing.JLabel();
        labelColor8Gama = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dialogCortarRegion = new javax.swing.JDialog();
        btnEnviarRegion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelFilaRegion = new javax.swing.JLabel();
        labelColumnaRegion = new javax.swing.JLabel();
        labelAnchoRegion = new javax.swing.JLabel();
        labelAltoRegion = new javax.swing.JLabel();
        textFilaRegion = new javax.swing.JTextField();
        textColumnaRegion = new javax.swing.JTextField();
        textAnchoRegion = new javax.swing.JTextField();
        textAltoRegion = new javax.swing.JTextField();
        btnCortarRegion = new javax.swing.JButton();
        btnCrearMarco = new javax.swing.JButton();
        bntFlipHorizontal = new javax.swing.JButton();
        btnPatronesGama = new javax.swing.JButton();
        btnInveritGama = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelLoading = new javax.swing.JPanel();
        labelLoading = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        dialogPatronGama.setMinimumSize(new java.awt.Dimension(300, 300));

        checkRedPatron.setBackground(new java.awt.Color(255, 0, 0));
        btnGroup.add(checkRedPatron);
        checkRedPatron.setText("   Rojo");
        checkRedPatron.setOpaque(false);
        checkRedPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRedPatronActionPerformed(evt);
            }
        });

        btnGroup.add(checkGreenPatron);
        checkGreenPatron.setText("   Verde");
        checkGreenPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGreenPatronActionPerformed(evt);
            }
        });

        btnGroup.add(checkBluePatron);
        checkBluePatron.setText("   Azul");
        checkBluePatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBluePatronActionPerformed(evt);
            }
        });

        btnEnviarPatron.setText("Enviar");
        btnEnviarPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPatronActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelColor2Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor2Patron.setText(" ");

        labelColor1Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor1Patron.setText(" ");

        labelColor3Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor3Patron.setText(" ");

        labelColor4Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor4Patron.setText(" ");

        labelColor5Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor5Patron.setText(" ");

        labelColor6Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor6Patron.setText(" ");

        labelColor7Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor7Patron.setText(" ");

        labelColor8Patron.setBackground(new java.awt.Color(255, 0, 0));
        labelColor8Patron.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColor1Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor2Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor3Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor4Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor5Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor6Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor7Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor8Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelColor1Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor2Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor3Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor4Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor5Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor6Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor7Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor8Patron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Detectar Patrones de Gama");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jLabel7.setText("Seleccione el color");

        javax.swing.GroupLayout dialogPatronGamaLayout = new javax.swing.GroupLayout(dialogPatronGama.getContentPane());
        dialogPatronGama.getContentPane().setLayout(dialogPatronGamaLayout);
        dialogPatronGamaLayout.setHorizontalGroup(
            dialogPatronGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dialogPatronGamaLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPatronGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPatronGamaLayout.createSequentialGroup()
                        .addGroup(dialogPatronGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkRedPatron)
                            .addComponent(checkGreenPatron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBluePatron, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPatronGamaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEnviarPatron)
                        .addGap(22, 22, 22))))
            .addGroup(dialogPatronGamaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogPatronGamaLayout.setVerticalGroup(
            dialogPatronGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPatronGamaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addGroup(dialogPatronGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPatronGamaLayout.createSequentialGroup()
                        .addComponent(checkRedPatron)
                        .addGap(17, 17, 17)
                        .addComponent(checkGreenPatron)
                        .addGap(17, 17, 17)
                        .addComponent(checkBluePatron)
                        .addGap(10, 10, 10)
                        .addComponent(btnEnviarPatron)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        dialogInvertirGama.setMinimumSize(new java.awt.Dimension(300, 300));

        checkRedGama.setBackground(new java.awt.Color(255, 0, 0));
        btnGroup.add(checkRedGama);
        checkRedGama.setText("   Rojo");
        checkRedGama.setOpaque(false);
        checkRedGama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRedGamaActionPerformed(evt);
            }
        });

        btnGroup.add(checkGreenGama);
        checkGreenGama.setText("   Verde");
        checkGreenGama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGreenGamaActionPerformed(evt);
            }
        });

        btnGroup.add(checkBlueGama);
        checkBlueGama.setText("   Azul");
        checkBlueGama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBlueGamaActionPerformed(evt);
            }
        });

        btnEnviarGama.setText("Enviar");
        btnEnviarGama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarGamaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelColor2Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor2Gama.setText(" ");

        labelColor1Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor1Gama.setText(" ");

        labelColor3Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor3Gama.setText(" ");

        labelColor4Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor4Gama.setText(" ");

        labelColor5Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor5Gama.setText(" ");

        labelColor6Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor6Gama.setText(" ");

        labelColor7Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor7Gama.setText(" ");

        labelColor8Gama.setBackground(new java.awt.Color(255, 0, 0));
        labelColor8Gama.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColor1Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor2Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor3Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor4Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor5Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor6Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor7Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor8Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelColor1Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor2Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor3Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor4Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor5Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor6Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor7Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelColor8Gama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel4.setForeground(new java.awt.Color(0, 0, 255));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Invertir Patrones de Gama");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Seleccione el color");

        javax.swing.GroupLayout dialogInvertirGamaLayout = new javax.swing.GroupLayout(dialogInvertirGama.getContentPane());
        dialogInvertirGama.getContentPane().setLayout(dialogInvertirGamaLayout);
        dialogInvertirGamaLayout.setHorizontalGroup(
            dialogInvertirGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dialogInvertirGamaLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogInvertirGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogInvertirGamaLayout.createSequentialGroup()
                        .addGroup(dialogInvertirGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkRedGama)
                            .addComponent(checkGreenGama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBlueGama, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogInvertirGamaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEnviarGama)
                        .addGap(22, 22, 22))))
            .addGroup(dialogInvertirGamaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogInvertirGamaLayout.setVerticalGroup(
            dialogInvertirGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInvertirGamaLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(16, 16, 16)
                .addGroup(dialogInvertirGamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogInvertirGamaLayout.createSequentialGroup()
                        .addComponent(checkRedGama)
                        .addGap(17, 17, 17)
                        .addComponent(checkGreenGama)
                        .addGap(17, 17, 17)
                        .addComponent(checkBlueGama)
                        .addGap(10, 10, 10)
                        .addComponent(btnEnviarGama)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        dialogCortarRegion.setMinimumSize(new java.awt.Dimension(300, 300));

        btnEnviarRegion.setText("Enviar");
        btnEnviarRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRegionActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel6.setForeground(new java.awt.Color(0, 0, 255));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Indique la region que desee cortar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Seleccione el color");

        labelFilaRegion.setText("Fila: ");

        labelColumnaRegion.setText("Columna:");

        labelAnchoRegion.setText("Ancho:");

        labelAltoRegion.setText("Alto:");

        javax.swing.GroupLayout dialogCortarRegionLayout = new javax.swing.GroupLayout(dialogCortarRegion.getContentPane());
        dialogCortarRegion.getContentPane().setLayout(dialogCortarRegionLayout);
        dialogCortarRegionLayout.setHorizontalGroup(
            dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dialogCortarRegionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCortarRegionLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCortarRegionLayout.createSequentialGroup()
                        .addComponent(btnEnviarRegion)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCortarRegionLayout.createSequentialGroup()
                        .addGroup(dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFilaRegion)
                            .addComponent(labelColumnaRegion)
                            .addComponent(labelAnchoRegion)
                            .addComponent(labelAltoRegion))
                        .addGap(25, 25, 25)
                        .addGroup(dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFilaRegion)
                            .addComponent(textColumnaRegion)
                            .addComponent(textAnchoRegion)
                            .addComponent(textAltoRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );
        dialogCortarRegionLayout.setVerticalGroup(
            dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCortarRegionLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilaRegion)
                    .addComponent(textFilaRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textColumnaRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColumnaRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAnchoRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnchoRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogCortarRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAltoRegion)
                    .addComponent(textAltoRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarRegion)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setMaximumSize(new java.awt.Dimension(667, 670));
        setMinimumSize(new java.awt.Dimension(667, 670));
        setPreferredSize(new java.awt.Dimension(667, 670));

        btnCortarRegion.setText("Cortar Region");
        btnCortarRegion.setBorder(null);
        btnCortarRegion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCortarRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCortarRegionActionPerformed(evt);
            }
        });

        btnCrearMarco.setText("Crear Marco");
        btnCrearMarco.setAutoscrolls(true);
        btnCrearMarco.setBorder(null);
        btnCrearMarco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrearMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMarcoActionPerformed(evt);
            }
        });

        bntFlipHorizontal.setText("Flip Horizontal");
        bntFlipHorizontal.setBorder(null);
        bntFlipHorizontal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntFlipHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntFlipHorizontalActionPerformed(evt);
            }
        });

        btnPatronesGama.setText("Patrones de Gama");
        btnPatronesGama.setBorder(null);
        btnPatronesGama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPatronesGama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatronesGamaActionPerformed(evt);
            }
        });

        btnInveritGama.setText("Invertir Gamas");
        btnInveritGama.setBorder(null);
        btnInveritGama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInveritGama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInveritGamaActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));

        labelLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/imagen/loading1.gif"))); // NOI18N

        javax.swing.GroupLayout panelLoadingLayout = new javax.swing.GroupLayout(panelLoading);
        panelLoading.setLayout(panelLoadingLayout);
        panelLoadingLayout.setHorizontalGroup(
            panelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoadingLayout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(labelLoading)
                .addGap(272, 272, 272))
        );
        panelLoadingLayout.setVerticalGroup(
            panelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoadingLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(labelLoading)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCortarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntFlipHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPatronesGama, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInveritGama, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearMarco, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnCortarRegion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnPatronesGama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnInveritGama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bntFlipHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(624, 624, 624))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 46, Short.MAX_VALUE)
                    .addComponent(panelLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnCortarRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCortarRegionActionPerformed
        // TODO add your handling code here:
        dialogCortarRegion.setBounds(970, 220, 300, 300);
        dialogCortarRegion.setVisible(true);               
        dialogCortarRegion.setResizable(false);
    }//GEN-LAST:event_btnCortarRegionActionPerformed

    private void btnCrearMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMarcoActionPerformed
        // TODO add your handling code here:
        p.crearMarco();
        this.crearMyMarco();
    }//GEN-LAST:event_btnCrearMarcoActionPerformed

    private void bntFlipHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntFlipHorizontalActionPerformed
        // TODO add your handling code here:
        p.flipOrizontal();
        this.detectarPatron();
    }//GEN-LAST:event_bntFlipHorizontalActionPerformed

    private void btnPatronesGamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatronesGamaActionPerformed
        // TODO add your handling code here:
               
        dialogPatronGama.setBounds(970, 220, 300, 300);
        dialogPatronGama.setVisible(true);               
        dialogPatronGama.setResizable(false);
        labelsColorGama(Color.white);
    }//GEN-LAST:event_btnPatronesGamaActionPerformed

    private void btnInveritGamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInveritGamaActionPerformed
        // TODO add your handling code here:               
        dialogInvertirGama.setBounds(970, 220, 300, 300);
        dialogInvertirGama.setVisible(true);               
        dialogInvertirGama.setResizable(false);
        labelsColorGama(Color.white);
        
    }//GEN-LAST:event_btnInveritGamaActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnEnviarPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPatronActionPerformed
        // TODO add your handling code here:
        
        
        try{
               
        String color = "";
        if(checkRedPatron.isSelected()){
            color = "rojo";
        }else if(checkGreenPatron.isSelected()){
            color = "verde";
        }else if(checkBluePatron.isSelected()){
            color = "azul";
        }else{
            throw new Exception();
        }
        p.detectarPatron(color);
        this.detectarPatron();
        dialogPatronGama.dispose();
        
        }catch(Exception ufps)
        {
            JOptionPane.showMessageDialog(null,"Por favor selecciona una gama","",0);
        }
    }//GEN-LAST:event_btnEnviarPatronActionPerformed

    private void checkRedPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRedPatronActionPerformed
        // TODO add your handling code here:
        labelsColorPatron(Color.red);
        
    }//GEN-LAST:event_checkRedPatronActionPerformed

    private void checkGreenPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGreenPatronActionPerformed
        // TODO add your handling code here:
        labelsColorPatron(Color.green);
    }//GEN-LAST:event_checkGreenPatronActionPerformed

    private void checkBluePatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBluePatronActionPerformed
        // TODO add your handling code here:
        labelsColorPatron(Color.blue);
    }//GEN-LAST:event_checkBluePatronActionPerformed

    private void checkRedGamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRedGamaActionPerformed
        // TODO add your handling code here:
        labelsColorGama(Color.red);
    }//GEN-LAST:event_checkRedGamaActionPerformed

    private void checkGreenGamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGreenGamaActionPerformed
        // TODO add your handling code here:
        labelsColorGama(Color.green);
    }//GEN-LAST:event_checkGreenGamaActionPerformed

    private void checkBlueGamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBlueGamaActionPerformed
        // TODO add your handling code here:
        labelsColorGama(Color.blue);
    }//GEN-LAST:event_checkBlueGamaActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnEnviarGamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarGamaActionPerformed
        // TODO add your handling code here:
        
        
        try{
        String color = "";
        if(checkRedGama.isSelected()){
            color = "rojo";
        }else if(checkGreenGama.isSelected()){
            color = "verde";
        }else if(checkBlueGama.isSelected()){
            color = "azul";
        }else{
            throw new Exception();
        }
        p.invertirGama(color);
        this.invertirGama();
        dialogInvertirGama.dispose();    
        
        }catch(Exception ufps)
        {
            JOptionPane.showMessageDialog(null,"Por favor selecciona una gama","",0);
        }
    }//GEN-LAST:event_btnEnviarGamaActionPerformed

    
    private void set()
    {
        this.textAltoRegion.setText(null);
        this.textAnchoRegion.setText(null);
        this.textColumnaRegion.setText(null);
        this.textFilaRegion.setText(null);
    }
    
    /**
     * 
     * @param fila
     * @param c
     * @param al
     * @param anc
     * @return 
     */
    private boolean esValido(int fila , int c , int al , int anc)
    {
       byte s1=(byte) (fila+anc);
       byte v1=(byte)(this.matrizBotones[fila].length);
       byte s2=(byte)(c+al);
       byte v2=(byte)(this.matrizBotones[c].length);
        
        boolean s=false;
       
        if(s1>v1 || s2>v2)
        {
             s=false;
        }
        else
        {
          s=true;
        }
          
        
        System.out.println(s+"");
        return s;
    } 
            
    /**
     * 
     * @param fila
     * @param col
     * @param alto
     * @param anc
     * @return 
     */
    private boolean esValido_Datos(int fila , int col,int alto , int anc)
    {
        if(fila<0 || col<0 || alto<0 || anc<0)
            return false;
        
        return true;
    }
    
    private void btnEnviarRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRegionActionPerformed
        // TODO add your handling code here:
        try{
        int fila = Integer.parseInt(this.textFilaRegion.getText());
        int columna = Integer.parseInt(this.textColumnaRegion.getText());
        int alto = Integer.parseInt(this.textAltoRegion.getText());
        int ancho = Integer.parseInt(this.textAnchoRegion.getText());
        
        if(esValido(fila,columna,alto,ancho) && esValido_Datos(fila,columna,alto,ancho))
        {
            p.cortar(fila, columna, ancho, alto);
            this.cortar(fila, columna, ancho, alto);
            dialogCortarRegion.dispose();
        }
        else
            this.set();
        
        }catch(Exception ufps)
        {
            JOptionPane.showMessageDialog(null,"Los datos ingresados no son validos","",0);
        }
        
        
        
    }//GEN-LAST:event_btnEnviarRegionActionPerformed

    
   /**
    * 
    * @param c 
    */


    private void labelsColorPatron(Color c){
        HSLColor base = new HSLColor(c);
        labelColor1Patron.setBackground( base.adjustTone(80) );
        labelColor2Patron.setBackground( base.adjustTone(70) );
        labelColor3Patron.setBackground( base.adjustTone(60) );
        labelColor4Patron.setBackground( base.adjustTone(50) );
        labelColor5Patron.setBackground( base.adjustTone(40) );
        labelColor6Patron.setBackground( base.adjustTone(30) );
        labelColor7Patron.setBackground( base.adjustTone(20) );
        labelColor8Patron.setBackground( base.adjustTone(10) );
        
        
        labelColor1Patron.setOpaque(true);
        labelColor2Patron.setOpaque(true);
        labelColor3Patron.setOpaque(true);
        labelColor4Patron.setOpaque(true);
        labelColor5Patron.setOpaque(true);
        labelColor6Patron.setOpaque(true);
        labelColor7Patron.setOpaque(true);
        labelColor8Patron.setOpaque(true);
    }
        private void labelsColorGama(Color c){
        HSLColor base = new HSLColor(c);
        labelColor1Gama.setBackground( base.adjustTone(80) );
        labelColor2Gama.setBackground( base.adjustTone(70) );
        labelColor3Gama.setBackground( base.adjustTone(60) );
        labelColor4Gama.setBackground( base.adjustTone(50) );
        labelColor5Gama.setBackground( base.adjustTone(40) );
        labelColor6Gama.setBackground( base.adjustTone(30) );
        labelColor7Gama.setBackground( base.adjustTone(20) );
        labelColor8Gama.setBackground( base.adjustTone(10) );
        
        
        labelColor1Gama.setOpaque(true);
        labelColor2Gama.setOpaque(true);
        labelColor3Gama.setOpaque(true);
        labelColor4Gama.setOpaque(true);
        labelColor5Gama.setOpaque(true);
        labelColor6Gama.setOpaque(true);
        labelColor7Gama.setOpaque(true);
        labelColor8Gama.setOpaque(true);
    }
    private void crear() {
        try {

            int n = this.p.getLength();
            int m = this.p.getFilaColores(0).getLength();

            int x;
            int y;
            this.matrizBotones = new JTextField[n][m];

            for (int i = 0; i < n; i++) {
                x = (((60-n)/2)+(i*1));
                for (int j = 0; j < m; j++) {
                    y = (((70-m)/2)+(j*1));
                    Border border = BorderFactory.createLineBorder(this.p.getFilaColores(i).get(j), 2, false);
                    
                    this.matrizBotones[i][j] = new JTextField("");
                    this.matrizBotones[i][j].setBounds((y*10), (x*10), 10, 10);
                    this.matrizBotones[i][j].setBorder(border);
                    
                    this.matrizBotones[i][j].setCursor(null);
                    this.matrizBotones[i][j].setEditable(false);
                    this.matrizBotones[i][j].setBackground(this.p.getFilaColores(i).get(j));
                    this.add(this.matrizBotones[i][j]);
                    if (i==n-1) {
                        this.panelLoading.setVisible(false);
                    }
                }
            }
            this.repaint();
        } catch (java.lang.NumberFormatException e) {
            throw new RuntimeException("Error de entrada de datos");
        } catch (java.lang.NegativeArraySizeException e) {
            throw new RuntimeException("cantidad<0");
        }

    }
    private void crearMyMarco(){
        
            int n = this.p.getLength();
            int m = this.p.getFilaColores(0).getLength();
            for (int i = 0; i < n; i++) {
                for (int j = 0; j < m; j++) {
                Border border = BorderFactory.createLineBorder(Color.BLACK, 2, false);

                this.matrizBotones[0][j].setBackground(this.p.getFilaColores(i).get(j));
                this.matrizBotones[0][j].setBorder(border);
                
                this.matrizBotones[i][0].setBackground(this.p.getFilaColores(i).get(j));
                this.matrizBotones[i][0].setBorder(border);
                
                this.matrizBotones[n-1][j].setBackground(this.p.getFilaColores(i).get(j));
                this.matrizBotones[n-1][j].setBorder(border);
                
                this.matrizBotones[i][m-1].setBackground(this.p.getFilaColores(i).get(j));
                this.matrizBotones[i][m-1].setBorder(border);                               
                }
            }
        
        
    }
    
    private void cortar(int fila, int columna, int ancho, int alto){
        for (int i = 0, k = columna; i < alto; i++, k++) {
            for (int j = 0, l = fila; j < ancho; j++, l++) {
                Border border = BorderFactory.createLineBorder(Color.WHITE, 2, false);
                this.matrizBotones[k][l].setBackground(this.p.getFilaColores(k).get(l));
                this.matrizBotones[k][l].setBorder(border); 
            }
        }

    }
    
    private void detectarPatron(){
            int n = this.p.getLength();
            int m = this.p.getFilaColores(0).getLength();
        for(int i =0; i < n; i++){
            for(int j = 0; j < m; j++){
                Border border = BorderFactory.createLineBorder(this.p.getFilaColores(i).get(j), 2, false);
                this.matrizBotones[i][j].setBackground(this.p.getFilaColores(i).get(j));
                this.matrizBotones[i][j].setBorder(border); 
            }
        }
    }
    private void invertirGama(){
            int n = this.p.getLength();
            int m = this.p.getFilaColores(0).getLength();
        for(int i =0; i < n; i++){
            for(int j = 0; j < m; j++){
                Border border = BorderFactory.createLineBorder(this.p.getFilaColores(i).get(j), 2, false);
                this.matrizBotones[i][j].setBackground(this.p.getFilaColores(i).get(j));
                this.matrizBotones[i][j].setBorder(border); 
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntFlipHorizontal;
    private javax.swing.JButton btnCortarRegion;
    private javax.swing.JButton btnCrearMarco;
    private javax.swing.JButton btnEnviarGama;
    private javax.swing.JButton btnEnviarPatron;
    private javax.swing.JButton btnEnviarRegion;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnInveritGama;
    private javax.swing.JButton btnPatronesGama;
    private javax.swing.JCheckBox checkBlueGama;
    private javax.swing.JCheckBox checkBluePatron;
    private javax.swing.JCheckBox checkGreenGama;
    private javax.swing.JCheckBox checkGreenPatron;
    private javax.swing.JCheckBox checkRedGama;
    private javax.swing.JCheckBox checkRedPatron;
    private javax.swing.JDialog dialogCortarRegion;
    private javax.swing.JDialog dialogInvertirGama;
    private javax.swing.JDialog dialogPatronGama;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelAltoRegion;
    private javax.swing.JLabel labelAnchoRegion;
    private javax.swing.JLabel labelColor1Gama;
    private javax.swing.JLabel labelColor1Patron;
    private javax.swing.JLabel labelColor2Gama;
    private javax.swing.JLabel labelColor2Patron;
    private javax.swing.JLabel labelColor3Gama;
    private javax.swing.JLabel labelColor3Patron;
    private javax.swing.JLabel labelColor4Gama;
    private javax.swing.JLabel labelColor4Patron;
    private javax.swing.JLabel labelColor5Gama;
    private javax.swing.JLabel labelColor5Patron;
    private javax.swing.JLabel labelColor6Gama;
    private javax.swing.JLabel labelColor6Patron;
    private javax.swing.JLabel labelColor7Gama;
    private javax.swing.JLabel labelColor7Patron;
    private javax.swing.JLabel labelColor8Gama;
    private javax.swing.JLabel labelColor8Patron;
    private javax.swing.JLabel labelColumnaRegion;
    private javax.swing.JLabel labelFilaRegion;
    private javax.swing.JLabel labelLoading;
    private javax.swing.JPanel panelLoading;
    private javax.swing.JTextField textAltoRegion;
    private javax.swing.JTextField textAnchoRegion;
    private javax.swing.JTextField textColumnaRegion;
    private javax.swing.JTextField textFilaRegion;
    // End of variables declaration//GEN-END:variables
}
